modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "${mod_github}/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
logoFile = "assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"
